spring:
  application:
    name: nifilili

  datasource:
    url: jdbc:postgresql://localhost:5432/nifilili_db
    username: sayedmuddassirhussain
    password: 060398
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true

  flyway:
    enabled: true

logging:
  level:
    org.flywaydb: INFO

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-access-expiration-ms: 900000
  jwt-refresh-expiration-ms: 2592000000

springdoc:
  swagger-ui:
    tagsSorter: alpha
